name: dbt_databricks_project
version: 1.0.0

profile: 'dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: view   # Default materialization

seeds:
  +quote_columns: false
  dbt_databricks_project:  # This must match your "name" above
    airports:              # CSV file name without `.csv`
      column_types:
        id: int
        ident: string
        type: string
        name: string
        latitude_deg: float
        longitude_deg: float
        elevation_ft: int
        continent: string
        iso_country: string
        iso_region: string
        municipality: string
        scheduled_service: string
        gps_code: string
        iata_code: string
        local_code: string
        home_link: string
        wikipedia_link: string
        keywords: string
    countries:
      column_types:
        id: int
        code: string
        name: string
        continent: string
        wikipedia_link: string
        keywords: string
    runways:
      column_types:
        id: int
        airport_ref: int
        airport_ident: string
        length_ft: int
        width_ft: int
        surface: string
        lighted: int
        closed: int
        le_ident: string
        le_latitude_deg: float
        le_longitude_deg: float
        le_elevation_ft: int
        le_heading_degT: float
        le_displaced_threshold_ft: int
        he_ident: string
        he_latitude_deg: float
        he_longitude_deg: float
        he_elevation_ft: int
        he_heading_degT: float
        he_displaced_threshold_ft: int

snapshots:
  +materialized: table