dbt:
  target: development
  outputs:
    development:
      type: databricks
      catalog: "{{ env_var('ENV') }}"
      schema:  "{{ env_var('DATABRICKS_SCHEMA') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      port: 443
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      organization: "{{ env_var('DATABRICKS_ORGANIZATION') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      threads: 10