name: DBT Azure Databricks Pipeline
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install dbt-databricks
    displayName: 'Install DBT Databricks'

  - script: |
      dbt deps
    displayName: 'Install DBT Dependencies'

  - script: |
      dbt run
    displayName: 'Run DBT Models'

  - script: |
      dbt test
    displayName: 'Run DBT Tests'

  - script: |
      bash scripts/databricks_job.sh
    displayName: 'Deploy to Databricks'